%% TradeOff_plot.m
% Plot the periodic and singular orbits of the trade-off model.
% Requires 'TradeOff_singular.mat' generated by 'TradeOff_singular.m'

%% Set Parameters
ep = .1;
a =- .1;
b = 3;
c = 1;
d = 2.8;
k = 1;
r = 10;
qMin = 0;
qMax = 1;

%% Set Equations
F = @(x, q) x .* (q + r - k * x);
G = @(x, y, q) x .* y .* (a * q.^2 + b * q + c) ./ (1 + x);
D = @(y, q) d * y;
E = @(x, y, q) 1 - y .* (2 * a * q + b) ./ (1 + x);

deq0 = @(x, y, q) [
                ep * (F(x, q) - G(x, y, q))
                ep * (G(x, y, q) - D(y, q))
                q * (1 - q) * E(x, y, q)
                ];

%% Set Numerics
de_opt = odeset('RelTol', 1e-6, 'AbsTol', 1e-6);

%% Preparation
deq = @(t, u) deq0(u(1), u(2), u(3));

%% Set Figure
fig1 = figure(1);
clf;
plot3(NaN, NaN, NaN);
hold on;
grid on;
view([-40 30]);
xlim([0 1]); % trait q
ylim([0 13]); % predator y
zlim([0 15]); % prey x
set(gca, 'YTickLabel', {}, 'ZTickLabel', {});
pbaspect([2 2 2]);
set(gca, 'FontSize', 14);

%% Draw Msw
qq = linspace(0, 1, 6);
xx = linspace(0, 15, 6);
[q, x] = meshgrid(qq, xx);
y = (1 + x) ./ (2 * a * q + b);
hMsw = surf(q, y, x);
ColorSW = (1/255) * [100 255 50];
set(hMsw, 'FaceColor', ColorSW);
set(hMsw, 'FaceAlpha', .6);
set(hMsw, 'EdgeColor', 'black');
set(hMsw, 'EdgeAlpha', .2);

%% Draw M0
lx = 4;
ly = 6;
xx = linspace(0, 15, lx);
yy = linspace(0, 13, ly);
[x, y] = meshgrid(xx, yy);
q = 0 * x;
Color0 = (1/255) * [150 100 255];
hM0 = surf(q, y, x);
set(hM0, 'FaceColor', Color0);
set(hM0, 'FaceAlpha', .4);
set(hM0, 'EdgeColor', 'black');
set(hM0, 'EdgeAlpha', .2);

%% Draw M1
q = [1 1 1 1];
x = [0 15 15 0];
y = [0 0 13 13];
Color1 = (1/255) * [100 100 150];
hM1 = fill3(q, y, x, Color1);
set(hM1, 'FaceAlpha', .2);
set(hM1, 'EdgeColor', 'none');

%% Draw Trajectory
Tmax = 2000;
x0 = 10;
y0 = .5;
q0 = .5;
u0 = [x0 y0 q0];
[tt, u] = ode23(deq, [0 Tmax], u0, de_opt);
ind = (tt > .9 * Tmax);
t = tt(ind);
x = u(ind, 1);
y = u(ind, 2);
q = u(ind, 3);
figure(1);
hper = plot3(q, y, x, 'r', 'LineWidth', 2);
xlabel('Trait (\alpha)', 'FontSize', 20);
ylabel('Predator (y)', 'FontSize', 20);
zlabel('Prey (x)', 'FontSize', 20);
grid on;

%% Draw Nearby Trajectory
Tmax = 1000;
x0 = 12; %10.23;
y0 = .5;
q0 = .5;
u0 = [x0 y0 q0];
[tt, u] = ode23(deq, [0 Tmax], u0, de_opt);
x = u(:, 1);
y = u(:, 2);
q = u(:, 3);
figure(1);
htraj = plot3(q, y, x, 'm', 'LineWidth', 2);
hxx = plot3(q0, y0, x0, 'mo');
uistack(hper, 'top');

%% Save Figure
filename = 'fig_TradeOff_nearby';
saveas(fig1, filename, 'png');

%% Duplicate Figure
ax1 = gca;
fig_per = figure(2);
copyobj(ax1, fig_per);
xlabel('Trait (\alpha)', 'FontSize', 20);
ylabel('Predator (y)', 'FontSize', 20);
zlabel('Prey (x)', 'FontSize', 20);

%% Disable Periodic Orbit
figure(1);
set(hper, 'Visible', 'off');
set(htraj, 'Visible', 'off');
set(hxx, 'Visible', 'off');

%% Draw Singular Orbit
load('cortez_sing.mat');
uu = uuA;
xxA = uu(:, 1);
yyA = uu(:, 2);
qqA = 0 * xxA;
x = xxA;
y = yyA;
q = qqA;
hsingA = plot3(q, y, x, 'b', 'LineWidth', 2);

uu = uuB;
xxB = uu(:, 1);
yyB = uu(:, 2);
qqB = 1 + 0 * xxB;
x = xxB;
y = yyB;
q = qqB;
hsingB = plot3(q, y, x, 'b', 'LineWidth', 2);

x = [xxA(1) xxB(end)];
y = [yyA(1) yyB(end)];
q = [qqA(1) qqB(end)];
plot3(q, y, x, 'r', 'LineWidth', 2);

x = [xxA(end) xxB(1)];
y = [yyA(end) yyB(1)];
q = [qqA(end) qqB(1)];
plot3(q, y, x, 'r', 'LineWidth', 2);

%% Continue Singular
xA = xxA(1);
yA = yyA(1);
xB = xxB(1);
yB = yyB(1);
plot3(0, yA, xA, 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 6);
plot3(0, yB, xB, 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 6);
plot3(1, yA, xA, 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 6);
plot3(1, yB, xB, 'ko', 'MarkerFaceColor', 'k', 'MarkerSize', 6);
text(0, yA, xA - 1.1, 'A_1', 'FontSize', 20);
text(0, yB, xB - 1.4, 'B_1', 'FontSize', 20);
text(1, yA, xA - 1.2, 'B_2', 'FontSize', 20);
text(1, yB - .4, xB, 'A_2', 'FontSize', 20);

deqM = @(x, y, q) [
                F(x, q) - G(x, y, q)
                G(x, y, q) - D(y, q)
                E(x, y, q)
                ];
deqM0 = @(t, u) deqM(u(1), u(2), qMin);
deqM1 = @(t, u) deqM(u(1), u(2), qMax);

u0 = [xA, yA, 0];
Tspan = [0, - .5];
[~, u] = ode23(deqM0, Tspan, u0, de_opt);
x = u(:, 1);
y = u(:, 2);
q = 0 * x;
plot3(q, y, x, 'b--', 'LineWidth', 1);

u0 = [xB, yB, 0];
Tspan = [0, 10];
[~, u] = ode23(deqM0, Tspan, u0, de_opt);
x = u(:, 1);
y = u(:, 2);
q = 0 * x;
plot3(q, y, x, 'b--', 'LineWidth', 1);

u0 = [xA, yA, 0];
Tspan = [0, 1];
[~, u] = ode23(deqM1, Tspan, u0, de_opt);
x = u(:, 1);
y = u(:, 2);
q = qMax + 0 * x;
plot3(q, y, x, 'b--', 'LineWidth', 2);

u0 = [xB, yB, 0];
Tspan = [0, -1];
[~, u] = ode23(deqM1, Tspan, u0, de_opt);
x = u(:, 1);
y = u(:, 2);
q = qMax + 0 * x;
plot3(q, y, x, 'b--', 'LineWidth', 2);

%% Get a point on the singular orbit
tmp = abs(q - .5);
ind0 = find(tmp == min(tmp), 1);
x0 = x(ind0);
y0 = y(ind0);
q0 = q(ind0);
disp([x0 y0 q0]);

%% Text
text(.2, 10, 8, '$\gamma_1$', 'Interpreter', 'latex', 'FontSize', 24, 'Color', 'r');
text(0, 5, 8, '$\sigma_1$', 'Interpreter', 'latex', 'FontSize', 24, 'Color', 'b');
text(.7, 1.5, 8.2, '$\gamma_2$', 'Interpreter', 'latex', 'FontSize', 24, 'Color', 'r');
text(1, 3.5, 10.5, '$\sigma_2$', 'Interpreter', 'latex', 'FontSize', 24, 'Color', 'b');

%% Save Figure
filename = 'fig_TradeOff_singular';
saveas(fig1, filename, 'png');
